# Generated by Django 4.2.7 on 2024-01-26 16:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="products",
            options={
                "ordering": ("id",),
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
